

// #define ST_LABSIMPLE_G071

#ifndef USE_MAKE
// #define F031_DEV
// #define FD6288_F051
// #define IFLIGHT
// #define MP6531
// #define TMOTOR55     // like iflight but with leds
// #define TMOTOR45
// #define HGLRC
// #define SISKIN
// #define MAMBA_F50PRO
// #define WRAITH32
// #define AIKON20X20
// #define AIKONSINGLE
// #define FLYCOLOR
// #define HKMICRO
// #define AM32REF_F051
// #define BLPWR
// #define HVFLYCOLOR
// #define AM32REF_F051

// #define G072ESC
// #define G071ENABLE
// #define G071_OPEN_DRAIN
// #define G071_OPEN_DRAIN_B
// #define GEN_64K_G071
// define  DT120_G071

// #define WRAITH32_F421
// #define GD32DEV
// #define GD32DEV_B
// #define GD32SKYSTARS20
// #define GD32SKYSTARS25
// #define GD32SKYSTARS30
// #define GD32SKYSTARS40
#endif

// used to hold a port/pin in a single 16 bit integer
#define GPIO_PORT_PIN(portnum, pinnum) ((portnum) << 8 | (pinnum))

// GLOBAL
// #define USE_ADC_INPUT
// #define USE_ALKAS_DEBUG_LED

/*******************************   G071 Targets
 * *********************************/

#ifdef AIRBOT_PHOENIX_12S_G071
#define FILE_NAME "AIRBOT_PHOENIX_12S_G071"
#define FIRMWARE_NAME "PHEONIX 12S "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 10
#define CURRENT_OFFSET 0
#define TARGET_STALL_PROTECTION_INTERVAL 9000
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_I
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_1
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_1

#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5

#define USE_LED_STRIP

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pb7

#endif

#ifdef RRIOT_G071
#define FILE_NAME "RRIOT_G071"
#define FIRMWARE_NAME "RRIOT G071"
#define DEAD_TIME 45
#define MILLIVOLT_PER_AMP 15
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_K
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef JUPITER_80_G071
#define FILE_NAME "JUPITER_80_G071"
#define FIRMWARE_NAME "JUPITER G071"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 30
#define CURRENT_OFFSET 40
#define HARDWARE_GROUP_G0_L
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define TARGET_VOLTAGE_DIVIDER 285
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#endif

#ifdef SKYSTARS_KM80_G071
#define FILE_NAME "SKYSTARS_KM80_G071"
#define FIRMWARE_NAME "SKYSTARS 80"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 30
#define CURRENT_OFFSET 40
#define HARDWARE_GROUP_G0_L
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef GEN_64K_G071
#define FILE_NAME "GEN_64K_G071"
#define FIRMWARE_NAME "G071 64kESC "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef TBS_4IN1_G071
#define FILE_NAME "TBS_4IN1_G071"
#define FIRMWARE_NAME "TBS 4N1 G071"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6
#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
#endif

#ifdef TBS_12S_G071
#define FILE_NAME "TBS_12S_G071"
#define FIRMWARE_NAME "TBS 12S G071"
#define DEAD_TIME 80
#define TARGET_VOLTAGE_DIVIDER 210
#define MILLIVOLT_PER_AMP 25
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6
#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#endif

#ifdef SP_CRUSTCORE_G071
#define FILE_NAME "SP_CRUSTCORE_G071"
#define FIRMWARE_NAME "Crustcore 60"
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef FLYCOLOR_G071
#define FILE_NAME "FLYCOLOR_G071"
#define FIRMWARE_NAME "FLYCOLOR_G0"
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef TMOTOR_F60A_G071
#define FILE_NAME "TMOTOR_F60A_G071"
#define FIRMWARE_NAME "F60A Mini G0"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef ST_G0_03_N_G071
#define FILE_NAME "ST_G0_03_N_G071"
#define FIRMWARE_NAME "ST_G0_03_N  "
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_H
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#endif

#ifdef ST_G0_04_G071
#define FILE_NAME "ST_G0_04_G071"
#define FIRMWARE_NAME "ST_G0_04    "
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_F
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_0
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_0
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#endif

#ifdef AIKON_04_G071
#define FILE_NAME "AIKON_04_G071"
#define FIRMWARE_NAME "AIKON_4_G071"
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_F
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_0
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_0
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define NO_PA11_PA12_REMAP
#endif

#ifdef AM32_ESC_G071
#define FILE_NAME "AM32_ESC_G071"
#define FIRMWARE_NAME "AM32ESC_G071"
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 16
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_4
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_6
#define CURRENT_ADC_PIN LL_GPIO_PIN_6
#define USE_LED_STRIP
#endif

#ifdef SEQURE_4IN1_G071
#define FILE_NAME "SEQURE_4IN1_G071"
#define FIRMWARE_NAME "Sequre 4in1 "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 9
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define TARGET_VOLTAGE_DIVIDER 210
#define SIXTY_FOUR_KB_MEMORY
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#endif

#ifdef AORC_GP_G071 // GP version
#define FILE_NAME "AORC_GP_G071"
#define FIRMWARE_NAME "AORC_GP_G071"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef AORC_PD_G071 // N variant
#define FILE_NAME "AORC_PD_G071"
#define FIRMWARE_NAME "AORC_PD_G071"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_G
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define USE_LED_STRIP
#endif

#ifdef TMOTOR_G071
#define FILE_NAME "TMOTOR_G071"
#define FIRMWARE_NAME "T-Motor G071"
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_H
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef DAKEFPV_G071
#define FILE_NAME "DAKEFPV_G071"
#define FIRMWARE_NAME "DAKEFPV_G071"
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_H
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef IFLIGHT_BLITZ_N_G071
#define FILE_NAME "IFLIGHT_BLITZ_N_G071"
#define FIRMWARE_NAME "Blitz G071N "
#define DEAD_TIME 40
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_G
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define USE_LED_STRIP
#endif

#ifdef IFLIGHT_12S_SINGLE_N_G071
#define FILE_NAME "IFLIGHT_12S_SINGLE_N_G071"
#define FIRMWARE_NAME "12s G071N "
#define DEAD_TIME 100
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_G
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#define TARGET_MIN_BEMF_COUNTS 4
#define USE_LED_STRIP
#endif

#ifdef SEQURE_G071
#define FILE_NAME "SEQURE_G071"
#define FIRMWARE_NAME "SEQURE G071 "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 33
#define CURRENT_OFFSET 0
#define TARGET_STALL_PROTECTION_INTERVAL 7000
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define USE_LED_STRIP
#endif

#ifdef SEQURE_HV_G071
#define FILE_NAME "SEQURE_HV_G071"
#define FIRMWARE_NAME "SEQURE HV  "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 11
// #define CURRENT_OFFSET 40
#define TARGET_STALL_PROTECTION_INTERVAL 9000
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#define TARGET_MIN_BEMF_COUNTS 3
#define USE_LED_STRIP
#define USE_PULSE_OUT
#define RPM_PULSE_PORT GPIOB
#define RPM_PULSE_PIN LL_GPIO_PIN_5
#endif

#ifdef SEQURE_TOP_G071
#define FILE_NAME "SEQURE_TOP_G071"
#define FIRMWARE_NAME "SEQURE TOP  "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 5
#define TARGET_STALL_PROTECTION_INTERVAL 9000
#define TARGET_VOLTAGE_DIVIDER 480
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4
#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#define TARGET_MIN_BEMF_COUNTS 3
#define USE_LED_STRIP
#define USE_PULSE_OUT
#define RPM_PULSE_PORT GPIOB
#define RPM_PULSE_PIN LL_GPIO_PIN_5
#endif

#ifdef MAMBA_S80_12S_G071
#define FILE_NAME "MAMBA_S80_12S_G071"
#define FIRMWARE_NAME "MAMBA S80   "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 10
#define CURRENT_OFFSET 0
#define TARGET_STALL_PROTECTION_INTERVAL 9000
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_J
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_1
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_1

#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5

#define USE_LED_STRIP
#endif

#ifdef HAKRC_2023_G071
#define FILE_NAME "HAKRC_2023_G071"
#define FIRMWARE_NAME "HAKRC G0_23 "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 45
#define CURRENT_OFFSET 515
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_I
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define USE_LED_STRIP
#endif

#ifdef NEUTRONRC_G071
#define FILE_NAME "NEUTRONRC_G071"
#define FIRMWARE_NAME "NeutronRC G0"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 33
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_N
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef ILLICITFPV_12S_AIO_G071
#define FILE_NAME "ILLICITFPV_12S_AIO_G071"
#define FIRMWARE_NAME "ILLICITFPV_G"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 33
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_N
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef NEUTRON_PULLUP_G071
#define FILE_NAME "NEUTRON_PULLUP_G071"
#define FIRMWARE_NAME "Neutron PU G"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 33
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_N
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef SURFBEE_G071
#define FILE_NAME "SURFBEE_G071"
#define FIRMWARE_NAME "SurfBee 4in1"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_N
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef FLYCOLOR_HV3_G071
#define FILE_NAME "FLYCOLOR_HV3_G071"
#define FIRMWARE_NAME "Flycolor HV3"
#define DEAD_TIME 80
#define MILLIVOLT_PER_AMP 33
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_N
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef AIKON_PRO_G071
#define FILE_NAME "AIKON_PRO_G071"
#define FIRMWARE_NAME "AIKON PRO 50"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_G
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef GEN_128K_G071
#define FILE_NAME "GEN_128K_G071"
#define FIRMWARE_NAME "G071 DevESC "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 15
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#endif

#ifdef IFLIGHT_BLITZ_G071
#define FILE_NAME "IFLIGHT_BLITZ_G071"
#define FIRMWARE_NAME "Blitz 55 G0 "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 15
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_F
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef IFLIGHT_12S_G071
#define FILE_NAME "IFLIGHT_12S_G071"
#define FIRMWARE_NAME "Iflight 12S "
#define DEAD_TIME 80
#define HARDWARE_GROUP_G0_F
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_0
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_0
#define RAMP_SPEED_LOW_RPM 1
#define RAMP_SPEED_HIGH_RPM 1
#define TARGET_MIN_BEMF_COUNTS 4
#endif

#ifdef DT120_G071
#define FILE_NAME "DT120_G071"
#define FIRMWARE_NAME "G071 120 DT "
#define DEAD_TIME 120
#define MILLIVOLT_PER_AMP 15
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#endif

#ifdef DT120_64K_G071
#define FILE_NAME "DT120_64K_G071"
#define FIRMWARE_NAME "G071 120 64K"
#define DEAD_TIME 120
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef DT160_64K_G071
#define FILE_NAME "DT160_64K_G071"
#define FIRMWARE_NAME "G071 160 64K"
#define DEAD_TIME 210
#define MILLIVOLT_PER_AMP 67
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_A
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef PWM_ENABLE_G071
#define FILE_NAME "PWM_ENABLE_G071"
#define FIRMWARE_NAME "G071 PWM_EN "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_B
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef OPEN_DRAIN_G071
#define FILE_NAME "OPEN_DRAIN_G071"
#define FIRMWARE_NAME "G071 TEENSY "
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_C
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef OPEN_DRAIN_B_G071
#define FILE_NAME "OPEN_DRAIN_B_G071"
#define FIRMWARE_NAME "G071 TEENSYB"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 20
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_D
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef ST_G0_06_N_G071
#define FILE_NAME "ST_G0_06_N_G071"
#define FIRMWARE_NAME "G0_06_N_G071"
#define DEAD_TIME 50
#define MILLIVOLT_PER_AMP 15
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 110
#define HARDWARE_GROUP_G0_G
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef STELLAR_G071_V1
#define FILE_NAME "STELLAR_G071_V1"
#define FIRMWARE_NAME "Stellar V1"
#define DEAD_TIME 80
#define MILLIVOLT_PER_AMP 15
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 210
#define HARDWARE_GROUP_G0_N
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef LUMENIER_SIEGE_G071
#define FILE_NAME "LUMENIER_SIEGE_G071"
#define FIRMWARE_NAME "SIEGE NDAA"
#define DEAD_TIME 60
#define MILLIVOLT_PER_AMP 10
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_K
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef LMNR_SIEGE_80A8S_4IN1_G071
#define FILE_NAME "LMNR_SIEGE_80A8S_4IN1_G071"
#define FIRMWARE_NAME "LS4_80A8S"
#define DEAD_TIME 25
#define MILLIVOLT_PER_AMP 24
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 130
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef LMNR_SIEGE_100A8S_SINGLE_G071
#define FILE_NAME "LMNR_SIEGE_100A8S_SINGLE_G071"
#define FIRMWARE_NAME "LSS_100A8S"
#define DEAD_TIME 25
#define MILLIVOLT_PER_AMP 24
#define CURRENT_OFFSET 0
#define TARGET_VOLTAGE_DIVIDER 130
#define HARDWARE_GROUP_G0_A
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifdef ST_G0_05_G071
#define FILE_NAME "ST_G0_05_G071"
#define FIRMWARE_NAME "ST_G0_05"
#define DEAD_TIME 45
#define MILLIVOLT_PER_AMP 10
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_K
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

// Based on ST_G0_05_G071
#ifdef ST_LABSIMPLE_G071
#define FILE_NAME "ST_LABSIMPLE_G071"
#define FIRMWARE_NAME "ST_LABSIMPLE"
#define DEAD_TIME 45
#define MILLIVOLT_PER_AMP 10
#define CURRENT_OFFSET 0
#define HARDWARE_GROUP_G0_M
#define USE_SERIAL_TELEMETRY
#define SIXTY_FOUR_KB_MEMORY
#endif

#ifndef FIRMWARE_NAME
/* if you get this then you have forgotten to add the section for your target above */
#error "Missing defines for target"
#endif

/********************************** defaults if not set
 * ***************************/

#ifndef TARGET_VOLTAGE_DIVIDER
#define TARGET_VOLTAGE_DIVIDER 110
#endif

#ifndef SINE_DIVIDER
#define SINE_DIVIDER 2
#endif

#ifndef MILLIVOLT_PER_AMP
#define MILLIVOLT_PER_AMP 20
#endif

#ifndef CURRENT_OFFSET
#define CURRENT_OFFSET 0
#endif

#ifndef TARGET_STALL_PROTECTION_INTERVAL
#define TARGET_STALL_PROTECTION_INTERVAL 6500
#endif

#ifndef RAMP_SPEED_STARTUP
#define RAMP_SPEED_STARTUP 2 // adjusted 2.14 to match duty cycle change between mcu targets.
#endif

#ifndef RAMP_SPEED_LOW_RPM // below commutation interval of 250us
#define RAMP_SPEED_LOW_RPM 6
#endif

#ifndef RAMP_SPEED_HIGH_RPM
#define RAMP_SPEED_HIGH_RPM 16
#endif

/************************************* G071 Hardware Groups ********************
 * ****************************************************************************/

#ifdef HARDWARE_GROUP_G0_A

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_B

#define MCU_G071
#define PWM_ENABLE_BRIDGE
#define USE_TIMER_3_CHANNEL_1

#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_PWM LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_PWM GPIOA
#define PHASE_A_GPIO_ENABLE LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_ENABLE GPIOB

#define PHASE_B_GPIO_PWM LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_PWM GPIOA
#define PHASE_B_GPIO_ENABLE LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_ENABLE GPIOB

#define PHASE_C_GPIO_PWM LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_PWM GPIOA
#define PHASE_C_GPIO_ENABLE LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_ENABLE GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_C

#define MCU_G071
#define OPEN_DRAIN_PWM
#define PWM_ENABLE_BRIDGE
#define USE_TIMER_3_CHANNEL_1

#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_PWM LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_PWM GPIOA
#define PHASE_A_GPIO_ENABLE LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_ENABLE GPIOB

#define PHASE_B_GPIO_PWM LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_PWM GPIOA
#define PHASE_B_GPIO_ENABLE LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_ENABLE GPIOB

#define PHASE_C_GPIO_PWM LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_PWM GPIOA
#define PHASE_C_GPIO_ENABLE LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_ENABLE GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_D

#define MCU_G071
#define OPEN_DRAIN_PWM
#define PWM_ENABLE_BRIDGE
#define USE_TIMER_3_CHANNEL_1

#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_PWM LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_PWM GPIOA
#define PHASE_A_GPIO_ENABLE LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_ENABLE GPIOA

#define PHASE_B_GPIO_PWM LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_PWM GPIOA
#define PHASE_B_GPIO_ENABLE LL_GPIO_PIN_6
#define PHASE_B_GPIO_PORT_ENABLE GPIOC

#define PHASE_C_GPIO_PWM LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_PWM GPIOA
#define PHASE_C_GPIO_ENABLE LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_ENABLE GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#endif

#ifdef HARDWARE_GROUP_G0_F

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_G

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa0

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_C_COMP_NUMBER COMP1

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G0_H

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_16_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM16
#define IC_TIMER_POINTER htim16

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim16_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa0

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_C_COMP_NUMBER COMP1

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G0_M

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa0

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_C_COMP_NUMBER COMP2

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G0_N

#define USE_LED_STRIP
#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G0_I

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#ifndef PHASE_A_COMP
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#endif
#ifndef PHASE_B_COMP
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#endif
#ifndef PHASE_C_COMP
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#endif

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_1
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_1

#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5

#endif

#ifdef HARDWARE_GROUP_G0_J

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_12
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_11
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa2

#endif

#ifdef HARDWARE_GROUP_G0_K

#define MCU_G071
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pb3
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pb7

#endif

#ifdef HARDWARE_GROUP_G0_L

#define MCU_G071
#define N_VARIANT
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOC
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO3 // pa2
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pb7

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_17
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_18
#define PHASE_C_COMP_NUMBER COMP2

#endif

#ifdef HARDWARE_GROUP_G4_A

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_A_GPIO_PORT_LOW GPIOF
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#ifdef COMP_OVERRIDE

#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 //

#define PHASE_B_INPUT_PLUS LL_COMP_INPUT_PLUS_IO2 // pa3
#define PHASE_A_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_C_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#else

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 //
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 //

#define PHASE_A_INPUT_PLUS LL_COMP_INPUT_PLUS_IO2 // pa3
#define PHASE_B_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_C_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_A_COMP_NUMBER COMP2

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#endif

// #define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
// #define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

// #define CURRENT_ADC_PIN LL_GPIO_PIN_4
// #define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G4_B

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pa4
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pa0

#define PHASE_A_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_B_INPUT_PLUS LL_COMP_INPUT_PLUS_IO2 // pa3
#define PHASE_C_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_B_COMP_NUMBER COMP2

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_G4_C

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_A_GPIO_PORT_LOW GPIOF
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pa4
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO1 // pa5

#define PHASE_A_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_B_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_C_INPUT_PLUS LL_COMP_INPUT_PLUS_IO2 // pa3

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_A_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_C_COMP_NUMBER COMP2

#endif

#ifdef HARDWARE_GROUP_G4_D

#define MCU_G431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define AF_A_LOW LL_GPIO_AF_4
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO2 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO1 // pa4
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO1 // pa5

#define PHASE_C_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_B_INPUT_PLUS LL_COMP_INPUT_PLUS_IO1 // pa1
#define PHASE_A_INPUT_PLUS LL_COMP_INPUT_PLUS_IO2 // pa3

#define PHASE_C_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_C_COMP_NUMBER COMP1

#define PHASE_B_EXTI_LINE LL_EXTI_LINE_21
#define PHASE_B_COMP_NUMBER COMP1

#define PHASE_A_EXTI_LINE LL_EXTI_LINE_22
#define PHASE_A_COMP_NUMBER COMP2

#endif

/************************************ G031 Hardware Groups
 * ************************************************/

#ifdef HARDWARE_GROUP_F031_A

#define EXTI_TYPE_BAC
#define USE_TIMER_2_CHANNEL_3
#define MCU_F031

#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH3
#define IC_TIMER_REGISTER TIM2
#define IC_TIMER_POINTER htim2

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim2_ch3
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOF
#define PHASE_B_EXTI_PORT GPIOF
#define PHASE_C_EXTI_PORT GPIOA

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_0
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_1
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_6

#define PHASE_A_EXTI_LINE 0
#define PHASE_B_EXTI_LINE 1
#define PHASE_C_EXTI_LINE 6

#define SYSCFG_EXTI_PORTA LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTB LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTC LL_SYSCFG_EXTI_PORTA

#define SYSCFG_EXTI_LINEA LL_SYSCFG_EXTI_LINE0
#define SYSCFG_EXTI_LINEB LL_SYSCFG_EXTI_LINE1
#define SYSCFG_EXTI_LINEC LL_SYSCFG_EXTI_LINE6

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_0
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_1
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_6

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_7

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_7

#endif

#ifdef HARDWARE_GROUP_F031_B

#define MCU_F031
#define USE_TIMER_2_CHANNEL_3
#define INPUT_PIN LL_GPIO_PIN_2
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH3
#define IC_TIMER_REGISTER TIM2
#define IC_TIMER_POINTER htim2

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim2_ch3
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOF
#define PHASE_B_EXTI_PORT GPIOF
#define PHASE_C_EXTI_PORT GPIOA

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_0
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_1
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_5

#define PHASE_A_EXTI_LINE 0
#define PHASE_B_EXTI_LINE 1
#define PHASE_C_EXTI_LINE 5

#define SYSCFG_EXTI_PORTA LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTB LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTC LL_SYSCFG_EXTI_PORTA

#define SYSCFG_EXTI_LINEA LL_SYSCFG_EXTI_LINE0
#define SYSCFG_EXTI_LINEB LL_SYSCFG_EXTI_LINE1
#define SYSCFG_EXTI_LINEC LL_SYSCFG_EXTI_LINE5

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_0
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_1
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_5

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_4

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_3
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_F031_C

#define MCU_F031
#define USE_TIMER_16
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM16
#define IC_TIMER_POINTER htim16

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_3
#define DMA_HANDLE_TYPE_DEF hdma_tim16_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel2_3_IRQn

#define PHASE_A_EXTI_PORT GPIOF
#define PHASE_B_EXTI_PORT GPIOB
#define PHASE_C_EXTI_PORT GPIOB

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_0
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_1
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_7

#define PHASE_A_EXTI_LINE 0
#define PHASE_B_EXTI_LINE 1
#define PHASE_C_EXTI_LINE 7

#define SYSCFG_EXTI_PORTA LL_SYSCFG_EXTI_PORTF
#define SYSCFG_EXTI_PORTB LL_SYSCFG_EXTI_PORTB
#define SYSCFG_EXTI_PORTC LL_SYSCFG_EXTI_PORTB

#define SYSCFG_EXTI_LINEA LL_SYSCFG_EXTI_LINE0
#define SYSCFG_EXTI_LINEB LL_SYSCFG_EXTI_LINE1
#define SYSCFG_EXTI_LINEC LL_SYSCFG_EXTI_LINE7

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_0
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_1
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_7

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

/***********************************************************************************************************/

#ifdef HARDWARE_GROUP_GD_A

#define MCU_GDE23
#define INPUT_PIN GPIO_PIN_4
#define INPUT_PIN_AF GPIO_AF_1
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TIMER_CH_0
#define IC_TIMER_REGISTER TIMER2
#define INPUT_DMA_CHANNEL DMA_CH3
#define LED_TIMER_REGISTER TIMER14
#define LED_DMA_CHANNEL DMA_CH4
#define LED_USES_PA2
#define IC_DMA_IRQ_NAME DMA_Channel3_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP 0x61 // CMP_PA0
#define PHASE_B_COMP 0x41 // CMP_PA4
#define PHASE_C_COMP 0x51 // CMP_PA5

#endif

#ifdef HARDWARE_GROUP_GD_B

#define MCU_GDE23
#define INPUT_PIN GPIO_PIN_4
#define INPUT_PIN_AF GPIO_AF_1
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TIMER_CH_0
#define IC_TIMER_REGISTER TIMER2
#define INPUT_DMA_CHANNEL DMA_CH3
#define LED_TIMER_REGISTER TIMER14
#define LED_DMA_CHANNEL DMA_CH4
#define LED_USES_PA2
#define IC_DMA_IRQ_NAME DMA_Channel3_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PIN_8
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PIN_7
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP 0x61 // CMP_PA0
#define PHASE_B_COMP 0x41 // CMP_PA4
#define PHASE_C_COMP 0x51 // CMP_PA5

#endif

#ifdef HARDWARE_GROUP_GD_C

#define MCU_GDE23
#define INPUT_PIN GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define INPUT_PIN_AF GPIO_AF_0
#define IC_TIMER_CHANNEL TIMER_CH_0
#define IC_TIMER_REGISTER TIMER14
#define INPUT_DMA_CHANNEL DMA_CH4
#define LED_TIMER_REGISTER TIMER2
#define LED_DMA_CHANNEL DMA_CH3
#define LED_USES_PB4
#define IC_DMA_IRQ_NAME DMA_Channel3_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_COMP 0x61 // CMP_PA0
#define PHASE_B_COMP 0x51 // CMP_PA5
#define PHASE_C_COMP 0x41 // CMP_PA4

#endif

#ifdef HARDWARE_GROUP_AT_B

#define MCU_AT421
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN GPIO_PINS_4
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR3
#define INPUT_DMA_CHANNEL DMA1_CHANNEL4
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_C

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_D

#define MCU_AT415
#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN GPIO_PINS_4
#define INPUT_PIN_PORT GPIOB
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR3
#define INPUT_DMA_CHANNEL DMA1_CHANNEL6
#define IC_DMA_IRQ_NAME DMA1_Channel6_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PIN_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PIN_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PIN_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PIN_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PIN_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PIN_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_H

#define MCU_AT415
#define USE_TIMER_2_CHANNEL_3
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_3
#define IC_TIMER_REGISTER TMR2
#define INPUT_DMA_CHANNEL DMA1_CHANNEL6
#define IC_DMA_IRQ_NAME DMA1_Channel6_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PIN_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PIN_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PIN_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PIN_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PIN_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PIN_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_E

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
// #define USE_PA14_TELEMETRY
#define USE_PA6_TEMP
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_0
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_7
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_F

#define MCU_AT421
#define USE_TIMER_15_CHANNEL_1
// #define USE_PA14_TELEMETRY
// #define USE_PA6_TEMP
#define INPUT_PIN GPIO_PINS_2
#define INPUT_PIN_SOURCE GPIO_PINS_SOURCE2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL TMR_SELECT_CHANNEL_1
#define IC_TIMER_REGISTER TMR15
#define INPUT_DMA_CHANNEL DMA1_CHANNEL5
#define IC_DMA_IRQ_NAME DMA1_Channel5_4_IRQn

#define PHASE_A_GPIO_LOW GPIO_PINS_1
#define PHASE_A_PIN_SOURCE_LOW GPIO_PINS_SOURCE1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_PINS_10
#define PHASE_A_PIN_SOURCE_HIGH GPIO_PINS_SOURCE10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_PINS_7
#define PHASE_B_PIN_SOURCE_LOW GPIO_PINS_SOURCE7
#define PHASE_B_GPIO_PORT_LOW GPIOA
#define PHASE_B_GPIO_HIGH GPIO_PINS_9
#define PHASE_B_PIN_SOURCE_HIGH GPIO_PINS_SOURCE9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_PINS_0
#define PHASE_C_PIN_SOURCE_LOW GPIO_PINS_SOURCE0
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH GPIO_PINS_8
#define PHASE_C_PIN_SOURCE_HIGH GPIO_PINS_SOURCE8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

#ifdef HARDWARE_GROUP_AT_045
#define PHASE_A_COMP 0x400000E5 // pa0 Medium Comp Power
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif
#ifdef HARDWARE_GROUP_AT_504
#define PHASE_A_COMP 0x400000D5 // pa5
#define PHASE_B_COMP 0x400000E5 // pa0
#define PHASE_C_COMP 0x400000C5 // pa4
#endif
#ifdef HARDWARE_GROUP_AT_450
#define PHASE_A_COMP 0x400000C5 // pa4
#define PHASE_B_COMP 0x400000D5 // pa5
#define PHASE_C_COMP 0x400000E5 // pa0
#endif
#ifdef HARDWARE_GROUP_AT_054
#define PHASE_A_COMP 0x400000E5 // pa0
#define PHASE_B_COMP 0x400000D5 // pa5
#define PHASE_C_COMP 0x400000C5 // pa4
#endif
#ifdef HARDWARE_GROUP_AT_405
#define PHASE_A_COMP 0x400000C5 // pa4
#define PHASE_B_COMP 0x400000E5 // pa0
#define PHASE_C_COMP 0x400000D5 // pa5
#endif
#ifdef HARDWARE_GROUP_AT_540
#define PHASE_A_COMP 0x400000D5 // pa5
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000E5 // pa0
#endif

#ifdef HARDWARE_GROUP_AT_245
#define PHASE_A_COMP 0x400000F5 // pa2     // works for polling mode
#define PHASE_B_COMP 0x400000C5 // pa4
#define PHASE_C_COMP 0x400000D5 // pa5
#endif

#ifdef HARDWARE_GROUP_L4_A

#define MCU_L431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define USE_COMP_1

#ifdef COMP_ORDER_L4_A_045
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO4 // pa4
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO5 // pa5
#endif

#ifdef COMP_ORDER_L4_A_540
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO5 // pa5  /// THIS CONFIG FOR T-MOTOR
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO4 // pa4
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO3 // pa0
#endif

#define COMMON_COMP LL_COMP_INPUT_PLUS_IO3

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_11

#endif

#ifdef HARDWARE_GROUP_L4_B

#define MCU_L431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA

#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define USE_COMP_2
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO5 // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO4 // pa4
#define COMMON_COMP LL_COMP_INPUT_PLUS_IO1
// #define USE_LED_STRIP
// #define WS2812_PIN LL_GPIO_PIN_3

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_11
#define ADC_CHANNEL_TEMP LL_ADC_CHANNEL_6

#endif

#ifdef HARDWARE_GROUP_L4_C

#define MCU_L431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define USE_COMP_1

#define COMMON_COMP LL_COMP_INPUT_PLUS_IO3 // pa1

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_11

#endif

#ifdef HARDWARE_GROUP_L4_045
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO4 // pa4
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO5 // pa5
#endif

#ifdef HARDWARE_GROUP_L4_054
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO3 // pa0
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO5 // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO4 // pa4
#endif

#ifdef HARDWARE_GROUP_L4_N

#define MCU_L431
#define USE_TIMER_15_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_2
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM15
#define IC_TIMER_POINTER htim15

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_5
#define DMA_HANDLE_TYPE_DEF hdma_tim15_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define USE_COMP_2
#define PHASE_A_COMP LL_COMP_INPUT_MINUS_IO2 // pb7
#define PHASE_B_COMP LL_COMP_INPUT_MINUS_IO5 // pa5
#define PHASE_C_COMP LL_COMP_INPUT_MINUS_IO4 // pa4
#define COMMON_COMP LL_COMP_INPUT_PLUS_IO1

#define CURRENT_SENSE_ADC_PIN LL_GPIO_PIN_3
#define VOLTAGE_SENSE_ADC_PIN LL_GPIO_PIN_6

#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_8
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_11

#endif

/************************************ G031 Hardware Groups
 * ************************************************/

#ifdef HARDWARE_GROUP_G031_A

#define MCU_G031
// #define EXTI_TYPE_BAC            // ??

#define USE_TIMER_3_CHANNEL_1
#define INPUT_PIN LL_GPIO_PIN_6
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL LL_TIM_CHANNEL_CH1
#define IC_TIMER_REGISTER TIM3
#define IC_TIMER_POINTER htim3

#define INPUT_DMA_CHANNEL LL_DMA_CHANNEL_1
#define DMA_HANDLE_TYPE_DEF hdma_tim3_ch1
#define IC_DMA_IRQ_NAME DMA1_Channel1_IRQn

#define PHASE_A_EXTI_PORT GPIOC
#define PHASE_B_EXTI_PORT GPIOB
#define PHASE_C_EXTI_PORT GPIOB

#define PHASE_A_EXTI_PIN LL_GPIO_PIN_14
#define PHASE_B_EXTI_PIN LL_GPIO_PIN_7
#define PHASE_C_EXTI_PIN LL_GPIO_PIN_1

#define PHASE_A_EXTI_LINE 14
#define PHASE_B_EXTI_LINE 7
#define PHASE_C_EXTI_LINE 1

#define SYSCFG_EXTI_PORTA LL_EXTI_CONFIG_PORTC
#define SYSCFG_EXTI_PORTB LL_EXTI_CONFIG_PORTB
#define SYSCFG_EXTI_PORTC LL_EXTI_CONFIG_PORTB

#define SYSCFG_EXTI_LINEA LL_EXTI_CONFIG_LINE14
#define SYSCFG_EXTI_LINEB LL_EXTI_CONFIG_LINE7
#define SYSCFG_EXTI_LINEC LL_EXTI_CONFIG_LINE1

#define PHASE_A_LL_EXTI_LINE LL_EXTI_LINE_14
#define PHASE_B_LL_EXTI_LINE LL_EXTI_LINE_7
#define PHASE_C_LL_EXTI_LINE LL_EXTI_LINE_1

#define EXTI_IRQ1_NAME EXTI0_1_IRQn
#define EXTI_IRQ2_NAME EXTI4_15_IRQn

// #define PHASE_A_GPIO_LOW LL_GPIO_PIN_15
// #define PHASE_A_GPIO_PORT_LOW GPIOB
// #define PHASE_A_GPIO_HIGH LL_GPIO_PIN_10
// #define PHASE_A_GPIO_PORT_HIGH GPIOA

// #define PHASE_B_GPIO_LOW LL_GPIO_PIN_14
// #define PHASE_B_GPIO_PORT_LOW GPIOB
// #define PHASE_B_GPIO_HIGH LL_GPIO_PIN_9
// #define PHASE_B_GPIO_PORT_HIGH GPIOA

// #define PHASE_C_GPIO_LOW LL_GPIO_PIN_13
// #define PHASE_C_GPIO_PORT_LOW GPIOB
// #define PHASE_C_GPIO_HIGH LL_GPIO_PIN_8
// #define PHASE_C_GPIO_PORT_HIGH GPIOA

#define PHASE_A_GPIO_LOW LL_GPIO_PIN_14
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH LL_GPIO_PIN_9
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW LL_GPIO_PIN_13
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH LL_GPIO_PIN_8
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW LL_GPIO_PIN_15
#define PHASE_C_GPIO_PORT_LOW GPIOB
#define PHASE_C_GPIO_HIGH LL_GPIO_PIN_10
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#define VOLTAGE_ADC_PIN LL_GPIO_PIN_5
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_5

#define CURRENT_ADC_PIN LL_GPIO_PIN_4
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_4

#endif

#ifdef HARDWARE_GROUP_CH_A

#define MCU_CH32V203
#define USE_TIMER_15_CHANNEL_1

#define INPUT_PIN GPIO_Pin_0
#define INPUT_PIN_PORT GPIOA
#define IC_TIMER_CHANNEL (1 - 1)
#define IC_TIMER_REGISTER TIM2
#define INPUT_DMA_CHANNEL DMA1_Channel5
#define IC_DMA_IRQ_NAME DMA1_Channel5_IRQn

#define PHASE_A_GPIO_LOW GPIO_Pin_1
#define PHASE_A_GPIO_PORT_LOW GPIOB
#define PHASE_A_GPIO_HIGH GPIO_Pin_10
#define PHASE_A_GPIO_PORT_HIGH GPIOA

#define PHASE_B_GPIO_LOW GPIO_Pin_0
#define PHASE_B_GPIO_PORT_LOW GPIOB
#define PHASE_B_GPIO_HIGH GPIO_Pin_9
#define PHASE_B_GPIO_PORT_HIGH GPIOA

#define PHASE_C_GPIO_LOW GPIO_Pin_7
#define PHASE_C_GPIO_PORT_LOW GPIOA
#define PHASE_C_GPIO_HIGH GPIO_Pin_8
#define PHASE_C_GPIO_PORT_HIGH GPIOA

#endif

/************************************ MCU COMMON PERIPHERALS
 * **********************************************/

#ifdef MCU_G071
#define STMICRO
#define CPU_FREQUENCY_MHZ 64
#ifdef SIXTY_FOUR_KB_MEMORY
#define EEPROM_START_ADD (uint32_t)0x0800F800
#else
#define EEPROM_START_ADD (uint32_t)0x0801F800
#endif
#define INTERVAL_TIMER TIM2
#define TEN_KHZ_TIMER TIM6
#define UTILITY_TIMER TIM17
#define COM_TIMER TIM14
#define APPLICATION_ADDRESS 0x08001000
#define MAIN_COMP COMP2
#define EXTI_LINE LL_EXTI_LINE_18

#ifndef TARGET_MIN_BEMF_COUNTS
#define TARGET_MIN_BEMF_COUNTS 2
#endif
#define COMPARATOR_IRQ ADC1_COMP_IRQn
#define USE_ADC
#ifndef CURRENT_ADC_CHANNEL
#define CURRENT_ADC_CHANNEL LL_ADC_CHANNEL_5
#endif
#ifndef VOLTAGE_ADC_CHANNEL
#define VOLTAGE_ADC_CHANNEL LL_ADC_CHANNEL_6
#endif
#ifndef CURRENT_ADC_PIN
#define CURRENT_ADC_PIN LL_GPIO_PIN_5
#endif
#ifndef VOLTAGE_ADC_PIN
#define VOLTAGE_ADC_PIN LL_GPIO_PIN_6
#endif
#define DSHOT_PRIORITY_THRESHOLD 60
#define COM_TIMER_IRQ TIM14_IRQn
#endif

#ifndef LOOP_FREQUENCY_HZ
#define LOOP_FREQUENCY_HZ 20000
#endif

#define PID_LOOP_DIVIDER (LOOP_FREQUENCY_HZ / 1000)

// default to no DroneCAN support
#ifndef DRONECAN_SUPPORT
#define DRONECAN_SUPPORT 0
#elif DRONECAN_SUPPORT == 1
// all DroneCAN ESCs use 128k flash layout
#undef EEPROM_START_ADD
#define EEPROM_START_ADD (uint32_t)0x0801F800
#endif

#ifndef NOMINAL_PWM
// use a nominal PWM for commutation via TIM1 of 24kHz
#define NOMINAL_PWM 24000U
#endif

#ifndef TIM1_AUTORELOAD
// calculate commutation timer ARR based on a nominal 24kHz PWM
#define TIM1_AUTORELOAD ((uint16_t)(CPU_FREQUENCY_MHZ * 1000U * 1000U / NOMINAL_PWM) - 1)
#endif

#ifndef POLLING_MODE_THRESHOLD
#define POLLING_MODE_THRESHOLD 2000
#endif
